"""
FRIDAY OS - Planner Models.

Defines the core Pydantic schemas for the Intelligent Planner,
enforcing a strict structure for Execution Plans generated by the LLM.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class Risk(BaseModel):
    """Represents a potential risk identified during planning."""

    description: str = Field(..., description="Description of the risk.")
    severity: Literal["low", "medium", "high", "critical"] = Field(
        ..., description="Severity level of the risk."
    )
    mitigation: str = Field(..., description="Proposed mitigation strategy.")


class TaskStep(BaseModel):
    """A discrete step within an Execution Plan."""

    id: str = Field(..., description="Unique step identifier (e.g., 'step_1').")
    name: str = Field(..., description="Short name of the step.")
    description: str = Field(..., description="Detailed instructions for the step.")
    dependencies: list[str] = Field(
        default_factory=list,
        description="IDs of other steps that must complete before this one.",
    )
    assigned_agent: str | None = Field(
        None, description="Suggested agent role (e.g., 'coder', 'researcher')."
    )
    tool_name: str | None = Field(None, description="The specific tool to execute this step.")
    action: str | None = Field(None, description="The specific action the tool should perform.")
    kwargs: dict[str, Any] = Field(default_factory=dict, description="Arguments to pass to the tool action.")


class Intent(BaseModel):
    """Structured output for intent detection."""

    primary_intent: str = Field(
        ..., description="The main intent (e.g., 'create_file', 'query_data')."
    )
    complexity: Literal["low", "medium", "high"] = Field(
        ..., description="Estimated complexity of the request."
    )
    requires_planning: bool = Field(
        ..., description="Whether this request requires a full execution plan."
    )


class ExecutionPlan(BaseModel):
    """The final structured plan generated by the Planning Engine."""

    plan_version: str = Field(default="1.0", description="Version of this specific plan format.")
    planner_version: str = Field(
        default="1.0.0", description="Version of the planner engine that generated this."
    )
    goal: str = Field(..., description="The overarching goal extracted from the user request.")
    steps: list[TaskStep] = Field(..., description="The ordered sequence of execution steps.")
    required_tools: list[str] = Field(
        default_factory=list, description="Names of tools required to execute the plan."
    )
    required_memory: list[str] = Field(
        default_factory=list, description="Summary of memory/context required."
    )
    dependencies: list[str] = Field(
        default_factory=list, description="External dependencies required (e.g., software, files)."
    )
    risks: list[Risk] = Field(default_factory=list, description="Potential risks and mitigations.")
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in the plan's success (0.0 to 1.0)."
    )
    confidence_reason: str = Field(..., description="Explanation for the given confidence score.")
    verification_strategy: str = Field(
        ..., description="How to verify the plan has been successfully executed."
    )
    retry_strategy: str = Field(
        ..., description="General approach to handle failures during execution."
    )
    expected_output: str = Field(..., description="What the user expects to see upon completion.")
