"""
FRIDAY OS - Plan Validator.

Validates the Execution Plan generated by the LLM before returning it
to the execution pipeline. Ensures strict adherence to schema and
logical constraints.
"""

from __future__ import annotations

from backend.planner.models import ExecutionPlan
from backend.utils.exceptions import AgentError
from backend.utils.logger import get_logger

logger = get_logger(__name__)


class PlanValidator:
    """Validates the generated Execution Plan."""

    def validate(self, plan: ExecutionPlan) -> bool:
        """Run validation checks on the plan.

        Args:
            plan: The parsed ExecutionPlan object.

        Returns:
            True if valid. Raises an AgentError if invalid.

        Raises:
            AgentError: If validation fails.
        """
        logger.debug("validating_execution_plan", plan_version=plan.plan_version)

        # 1. Structural Checks
        if not plan.steps:
            raise AgentError(
                message="Plan validation failed: Plan contains zero steps.",
                error_code="PLAN_VALIDATION_NO_STEPS",
                agent_name="PlanValidator",
            )

        # 2. Dependency Checks
        step_ids = {step.id for step in plan.steps}
        for step in plan.steps:
            for dep in step.dependencies:
                if dep not in step_ids:
                    raise AgentError(
                        message=f"Plan validation failed: Step '{step.id}' depends on unknown step '{dep}'.",
                        error_code="PLAN_VALIDATION_MISSING_DEPENDENCY",
                        agent_name="PlanValidator",
                    )

        # 3. Confidence Threshold Check
        # If confidence is exceptionally low, we might reject the plan automatically
        # and force a retry or ask the user for clarification.
        if plan.confidence_score < 0.2:
            raise AgentError(
                message=f"Plan validation failed: Confidence score ({plan.confidence_score}) is too low. Reason: {plan.confidence_reason}",
                error_code="PLAN_VALIDATION_LOW_CONFIDENCE",
                agent_name="PlanValidator",
            )

        logger.info(
            "execution_plan_validated",
            steps=len(plan.steps),
            confidence=plan.confidence_score,
        )
        return True
